# Enable SYN Cookie protection
net.ipv4.tcp_syncookies = 1

# Ignore ICMP (Ping) requests to hide from scanners
net.ipv4.icmp_echo_ignore_all = 1

# Protection from Spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1